# Generated by extendr: Do not edit by hand

# nolint start

#
# This file was created with the following call:
#   .Call("wrap__make_stacrsr_wrappers", use_symbols = TRUE, package_name = "stacrsr")

#' @usage NULL
#' @useDynLib stacrsr, .registration = TRUE
NULL

#' Return string `"Hello world!"` to R.
#' @export
hello_world <- function() .Call(wrap__hello_world)

read <- function(href, format, options) .Call(wrap__read, href, format, options)


# nolint end
